name: Terraform CI (fmt/validate/plan)

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      YC_TOKEN: ${{ secrets.YC_TOKEN }}
      YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
      YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      # -------------------------
      # 00-bootstrap
      # -------------------------
      - name: Bootstrap | Prepare tfvars
        working-directory: 00-bootstrap
        run: |
          cat > terraform.tfvars <<EOF
          cloud_id     = "${YC_CLOUD_ID}"
          folder_id    = "${YC_FOLDER_ID}"
          bucket_name  = "${{ secrets.TF_STATE_BUCKET }}"
          EOF

      - name: Bootstrap | Init
        working-directory: 00-bootstrap
        run: terraform init -input=false

      - name: Bootstrap | Validate
        working-directory: 00-bootstrap
        run: terraform validate

      - name: Bootstrap | Plan
        working-directory: 00-bootstrap
        run: terraform plan -no-color -input=false

      # -------------------------
      # 10-main
      # -------------------------
      - name: Main | Prepare tfvars
        working-directory: 10-main
        run: |
          cat > terraform.tfvars <<EOF
          cloud_id  = "${YC_CLOUD_ID}"
          folder_id = "${YC_FOLDER_ID}"
          EOF

      - name: Main | Init (S3 backend)
        working-directory: 10-main
        run: |
          terraform init -reconfigure -input=false \
            -backend-config=backend.hcl \
            -backend-config="access_key=${{ secrets.TF_STATE_ACCESS_KEY }}" \
            -backend-config="secret_key=${{ secrets.TF_STATE_SECRET_KEY }}"

      - name: Main | Validate
        working-directory: 10-main
        run: terraform validate

      - name: Main | Plan
        working-directory: 10-main
        run: terraform plan -no-color -input=false
